CREATE TABLESPACE DEV_TS
DATAFILE 'C:/oraclexe/app/oracle/oradata/XE/dev_ts'
SIZE 50M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
/

/*
CREATE TABLESPACE PROD_TS
DATAFILE 'C:/oraclexe/app/oracle/oradata/XE/prod_ts'
SIZE 50M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
/
 
*/