PROMPT Creating Sequence 'USER_ID_SEQ'
CREATE SEQUENCE USER_ID_SEQ
	INCREMENT BY 1
	START WITH 1000
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'STORE_ID_SEQ'
CREATE SEQUENCE STORE_ID_SEQ
	INCREMENT BY 1
	START WITH 100
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'PRODUCT_ID_SEQ'
CREATE SEQUENCE PRODUCT_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'FEATURE_ID_SEQ'
CREATE SEQUENCE FEATURE_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	NOCACHE;
/

PROMPT Creating Sequence 'PRODUCT_FEATURES_ID_SEQ'
CREATE SEQUENCE PRODUCT_FEATURE_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'AUCTIONS_ID_SEQ'
CREATE SEQUENCE AUCTION_ID_SEQ
	INCREMENT BY 1
	START WITH 100
	NOMAXVALUE
	MINVALUE 100
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'STORE_PRODUCT_ID_SEQ'
CREATE SEQUENCE STORE_PRODUCT_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'BLACK_LIST_ID_SEQ'
CREATE SEQUENCE BLACK_LIST_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	NOCACHE;
/

PROMPT Creating Sequence 'BLACK_LIST_STORE_ID_SEQ'
CREATE SEQUENCE BLACK_LIST_STORE_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	NOCACHE;
/

PROMPT Creating Sequence 'REVIEW_ID_SEQ'
CREATE SEQUENCE REVIEW_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'OFFER_ID_SEQ'
CREATE SEQUENCE OFFER_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'USER_WATCHED_PROD_ID_SEQ'
CREATE SEQUENCE USER_WATCHED_PROD_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'Price_list_id_seq'
CREATE SEQUENCE PRICE_LIST_ID_SEQ
	INCREMENT BY 1
	START WITH 100
	NOMAXVALUE
	MINVALUE 100
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'Worker_Task_id_seq'
CREATE SEQUENCE WORKER_TASK_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'UU_conversation_id_seq'
CREATE SEQUENCE UU_CONVERSATION_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'SU_conversation_id_seq'
CREATE SEQUENCE SU_CONVERSATION_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'Store_message_id_seq'
CREATE SEQUENCE STORE_MESSAGE_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'User_message_id_seq'
CREATE SEQUENCE USER_MESSAGE_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'User_ticket_id_seq'
CREATE SEQUENCE USER_TICKET_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  MINVALUE 1
  NOCYCLE
  CACHE 20;
/

PROMPT Creating Sequence 'Store_ticket_id_seq'
CREATE SEQUENCE STORE_TICKET_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  MINVALUE 1
  NOCYCLE
  CACHE 20;
/

PROMPT Creating Sequence 'User_reply_id_seq'
CREATE SEQUENCE USER_REPLY_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  MINVALUE 1
  NOCYCLE
  CACHE 20;
/

PROMPT Creating Sequence 'Store_ticket_id_seq'
CREATE SEQUENCE STORE_TICKET_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  MINVALUE 1
  NOCYCLE
  CACHE 20;
/

PROMPT Creating Sequence 'Store_reply_id_seq'
CREATE SEQUENCE STORE_REPLY_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  MINVALUE 1
  NOCYCLE
  CACHE 20;
/

PROMPT Creating Sequence 'Admin_id_seq'
CREATE SEQUENCE ADMIN_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  MINVALUE 1
  NOCYCLE
  NOCACHE;
/

PROMPT Creating Sequence 'Admin_alert_id_seq'
CREATE SEQUENCE ADMIN_ALERT_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 10;
/

PROMPT Creating Sequence 'worker_task_hist_id_seq'
CREATE SEQUENCE WORKER_TASK_HIST_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'user_ticket_reply_id_seq'
CREATE SEQUENCE USER_TICKET_REPLY_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'store_ticket_reply_id_seq'
CREATE SEQUENCE STORE_TICKET_REPLY_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 20;
/

PROMPT Creating Sequence 'product_photo_id_seq'
CREATE SEQUENCE PRODUCT_PHOTO_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	NOCACHE;
/

PROMPT Creating Sequence 'photo_id_seq'
CREATE SEQUENCE PHOTO_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	NOCACHE;
/

PROMPT Creating Sequence 'store_photo_id_seq'
CREATE SEQUENCE STORE_PHOTO_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	NOCACHE;
/

PROMPT Creating Sequence 'store_user_id_seq'
CREATE SEQUENCE STORE_USER_ID_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 10;
/

CREATE SEQUENCE MESSAGE_ID_SEQ
INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 10;
/

*/

CREATE SEQUENCE REPLY_ID_SEQ
INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 10;
/

CREATE SEQUENCE TICKET_US_ID_SEQ
INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 10;
/

CREATE SEQUENCE TICKET_SA_ID_SEQ
INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 10;
/

CREATE SEQUENCE TICKET_UA_ID_SEQ
INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	MINVALUE 1
	NOCYCLE
	CACHE 10;
/

/* Created by Julia Osiak, PJWSTK 2014, Bachelor of Science Thesis */