source 'https://rubygems.org'
ruby '2.1.1'
gem 'rails', '4.1.1'

gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'bootstrap-sass'
gem 'jquery-rails'
gem 'haml-rails'
gem 'simple_form'
gem 'therubyracer', :platform=>:ruby
gem 'bcrypt-ruby', :require => 'bcrypt' 
gem 'ruby-oci8'
gem 'activerecord-oracle_enhanced-adapter', '~> 1.5.0'
gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_21]
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
   gem 'railroady'
end
