source 'https://rubygems.org'
ruby '2.1.0'
gem 'rails', '4.0.2'
# Use oracle as the database for Active Record
gem 'ruby-oci8'

#enhanced AR
gem 'activerecord-oracle_enhanced-adapter', '~> 1.5.0'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass', '>= 3.0.0.0'
gem 'figaro'
gem 'haml-rails'
gem 'mongoid', :github=>"mongoid/mongoid"
gem 'simple_form'
gem 'therubyracer', :platform=>:ruby
gem 'bcrypt-ruby', :require => 'bcrypt' 


#nlp
gem 'treetop'

#graphs
gem "nvd3-rails", :github => "adeven/nvd3-rails", :submodules => true

#datatables
gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'

#neo4j gem
gem 'neography'

gem 'carmen-rails'


#breadcrumbs
gem "breadcrumbs_on_rails"

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
   gem 'railroady'
end
group :production do
  gem 'thin'
end
