source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
ruby '2.1.1'
gem 'rails', '4.0.2'

# Use oracle as the database for Active Record
gem 'ruby-oci8'

#enhanced AR
gem 'activerecord-oracle_enhanced-adapter', '~> 1.5.0'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
#gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
#gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
#gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'


  # bundle exec rake doc:rails generates the API under doc/api.

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'bootstrap-sass', '>= 3.0.0.0'
gem 'jquery-rails'

gem 'haml-rails'
gem 'simple_form'
gem 'therubyracer', :platform=>:ruby

gem 'bcrypt-ruby', :require => 'bcrypt' 

gem 'will_paginate', '~> 3.0'
gem 'mongoid', :github=>"mongoid/mongoid"

gem 'carmen-rails'

#datatables
gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'#, :platforms=>[:mri_19, :mri_20, :rbx]
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'bullet'
   gem 'railroady'
end

group :production do
  gem 'thin'
end

